/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as EneagramaRouteImport } from './routes/eneagrama'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as MentoriasRouteImport } from './routes/mentorias'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as YogaRouteImport } from './routes/yoga'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EneagramaRoute = EneagramaRouteImport.update({
  id: '/eneagrama',
  path: '/eneagrama',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriasRoute = MentoriasRouteImport.update({
  id: '/mentorias',
  path: '/mentorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaRoute = YogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/eneagrama': typeof EneagramaRoute
  '/faq': typeof FaqRoute
  '/jornada': typeof JornadaRoute
  '/mentorias': typeof MentoriasRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/yoga': typeof YogaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/eneagrama': typeof EneagramaRoute
  '/faq': typeof FaqRoute
  '/jornada': typeof JornadaRoute
  '/mentorias': typeof MentoriasRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/yoga': typeof YogaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/eneagrama': typeof EneagramaRoute
  '/faq': typeof FaqRoute
  '/jornada': typeof JornadaRoute
  '/mentorias': typeof MentoriasRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/yoga': typeof YogaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/contato'
    | '/depoimentos'
    | '/eneagrama'
    | '/faq'
    | '/jornada'
    | '/mentorias'
    | '/servicos'
    | '/sobre'
    | '/yoga'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/contato'
    | '/depoimentos'
    | '/eneagrama'
    | '/faq'
    | '/jornada'
    | '/mentorias'
    | '/servicos'
    | '/sobre'
    | '/yoga'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/contato'
    | '/depoimentos'
    | '/eneagrama'
    | '/faq'
    | '/jornada'
    | '/mentorias'
    | '/servicos'
    | '/sobre'
    | '/yoga'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  ContatoRoute: typeof ContatoRoute
  DepoimentosRoute: typeof DepoimentosRoute
  EneagramaRoute: typeof EneagramaRoute
  FaqRoute: typeof FaqRoute
  JornadaRoute: typeof JornadaRoute
  MentoriasRoute: typeof MentoriasRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  YogaRoute: typeof YogaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eneagrama': {
      id: '/eneagrama'
      path: '/eneagrama'
      fullPath: '/eneagrama'
      preLoaderRoute: typeof EneagramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorias': {
      id: '/mentorias'
      path: '/mentorias'
      fullPath: '/mentorias'
      preLoaderRoute: typeof MentoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga': {
      id: '/yoga'
      path: '/yoga'
      fullPath: '/yoga'
      preLoaderRoute: typeof YogaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  ContatoRoute: ContatoRoute,
  DepoimentosRoute: DepoimentosRoute,
  EneagramaRoute: EneagramaRoute,
  FaqRoute: FaqRoute,
  JornadaRoute: JornadaRoute,
  MentoriasRoute: MentoriasRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  YogaRoute: YogaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
